version: 2

common_steps: &common_steps
  - checkout
  - run:
      name: Prepare environment
      command: |
        apt-get update
        apt-get install -y --no-install-recommends libssl-dev
        bundle install
  - run:
      name: Test
      command: bundle exec rake test

jobs:
  ruby233:
    docker:
      - image: ruby:2.3.3
    steps: *common_steps
  ruby237:
    docker:
      - image: ruby:2.3.7
    steps: *common_steps

workflows:
  version: 2
  build:
    jobs:
      - ruby233
      - ruby237
